baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Cody Swartz | The Man In Dark Clothing"
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 5
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 2
[[menu.main]]
URL = "about"
name = "About"
weight = 1
[params]
address = ""
author = "Cody Swartz"
copyright = "Copyright &copy; 2020"
description = "A place for my things..."
email = "cody.swartz@outlook.com"
google_analitycs_id = "Your ID"
home = "Home"
logo = "/images/cs-logo-temp-white.png"
phone = ""
theme_color = "#41228e"
[params.contact]
enable = true
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.facebook.com/Cody.S.Swartz"
icon = "ti-facebook"
[[params.social]]
URL = "https://github.com/CSwartzV6"
icon = "ti-github"
[[params.social]]
URL = "https://www.instagram.com/cody.swartz/"
icon = "ti-instagram"
